---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bogus-app
  namespace: lemonpi
  labels:
    app: bogus-app
  annotations:
    fluxcd.io/tag.init: regex:^3.10.*
    fluxcd.io/tag.bogus-appd: semver:~2.1
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: bogus-app
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: bogus-app
    spec:
      imagePullSecrets:
      - name: bogus-app-regcred
      containers:
      - name: bogus-app
        image: registry.gitlab.com/greenhousegroup/lemonpi/playground/bogus-app:v2.0.0-6-g9adfe72
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 1000m
            memory: 500Mi
